#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────────────────────
  pikaur -S --needed --noconfirm meson cpio cmake
# ──────────────────────────────────────────────────────────────────────────────────────────────
  hyprpm update
  hyprpm add https://github.com/hyprwm/hyprland-plugins
  hyprpm enable hyprfocus
# ──────────────────────────────────────────────────────────────────────────────────────────────
  mv $HOME/.config/hypr/psyarch/hyprfocus.off $HOME/.config/hypr/psyarch/hyprfocus.conf
# ──────────────────────────────────────────────────────────────────────────────────────────────
